#!/usr/bin/with-contenv bash
for var in $(env | grep "^FILE__" | cut -d= -f1); do
  file_path="${!var}"
  if [ -f "$file_path" ]; then
    value=$(cat "$file_path")
    new_var="${var#FILE__}"
    export "$new_var"="$value"
  fi
done