name: Test Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: local/audiobookshelf-s6:test
          push: false

      - name: Run and Test Image
        run: |
          docker run -d --name test-container -p 13378:80 local/audiobookshelf-s6:test
          sleep 10  # Warte auf Start
          curl -f http://localhost:13378/healthcheck || exit 1  # Passe an deinen Health-Endpoint an
          docker stop test-container